version: '3'
services:
  mediawiki:
    build: .
    #image: mediawiki:1.34.2
    restart: always
    container_name: wiki
    ports:
      - 8080:80
    volumes:
      - "./images:/var/www/html/images"
      - "./data:/var/www/data" 
      - "./backup:/var/www/backup"
