version: '3'
services:
  mediawiki:
    build: .
    restart: always
    container_name: wiki
    ports:
      - 8080:80
    environment:
      GMAIL_AUTH: ${GMAIL_AUTH}
    volumes:
      - "./images:/var/www/html/images"
      - "./data:/var/www/data" 
      - "./backup:/var/www/backup"
      - "./LocalSettings.php:/var/www/html/LocalSettings.php"
